parameters:
  EnvironmentName: 'Default'

jobs:
#####################################################################################
#             Job: Create ResourceGroup                                             #
#####################################################################################
- job: 'CreatingResourceGroup'  
  steps:

  # For dedicated subscriptions the resource group can be created any way you like. This pipeline uses Azure CLI.
  - task: AzureCLI@1
    displayName: 'Create Resource Group - Dedicated Subscription model'
    enabled: true
    name: 'create_rg_dedicated'
    inputs:
      azureSubscription: $(AzureSPNOTA)
      scriptLocation: 'inlineScript'
      inlineScript: |
        az group create --name $(ResourceGroupName) --location $(location) --tags "ProjectName=$(unique)"

  
     # Deploy the example infrastructure (Azure services) using the bicep template
  - task: AzureCLI@1
    displayName: 'Deploy SQL Server Using Bicep template'
    enabled: true
    name: 'Create_SQL'
    inputs:
      azureSubscription: $(AzureSPNOTA)
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment group create \
          --name Azure-Start \
          --resource-group $(ResourceGroupName) \
          --template-file "$(System.DefaultWorkingDirectory)/main.bicep" \
          --parameters main.parameters.json                       
